services:
  structkit-dry-run:
    build: .
    volumes:
      - .:/app
    entrypoint: ["python", "structkit/main.py"]
    env_file:
      - .env
    command: [
      "generate",
      "--log=DEBUG",
      "--dry-run",
      "--vars=project_name=MyProject,author_name=JohnDoe",
      "--backup=/app/backup",
      "--file-strategy=rename",
      "--log-file=/app/logfile.log",
      "/app/example/structure.yaml",
      "/app/example_project"
    ]
  structkit-test:
    build: .
    volumes:
      - .:/app
    entrypoint: ["python", "structkit/main.py"]
    env_file:
      - .env
    command: [
      "generate",
      "--log=DEBUG",
      "--vars=project_name=MyProject,author_name=JohnDoe",
      "--backup=/app/backup",
      "--file-strategy=rename",
      "--log-file=/app/logfile.log",
      "/app/example/structure.yaml",
      "/app/example_project"
    ]
